- include: apt.yml            tags=apt
- include: zotero.yml         tags=zotero
- include: ssl.yml            tags=ssl
- include: system.yml         tags=system
- include: db.yml             tags=db
- include: sv.yml             tags=sv
- include: build_client.yml             tags=client




# TODO:

# test!

# add users and groups! (maybe via phpmyadmin)

# make cert_override.txt



# PHP Warning:  Memcached::setOptions(): invalid serializer provided in /srv/zotero/dataserver/include/Memcached.inc.php on line 63


#read AWS_HOST
#sed -i "27a\ \ \ \ \ \ \ \ public static \$AWS_HOST\ =\ '${AWS_HOST};'" /srv/zotero/dataserver/include/config/config.inc.php

#sed -i "225a \$awsconfig['base_url']\ =\ ZCONFIG::\$AWS_HOST;" /srv/zotero/dataserver/include/header.inc.php

# TODO: fix relax-ng
# or not required already?

